# Generated by Django 3.2.16 on 2023-02-01 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRP', '0003_auto_20230130_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario_a',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('dni', models.PositiveIntegerField(default=0, max_length=8, unique=True, verbose_name=' Nro. de Documento')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='usuario',
            name='dni',
            field=models.PositiveIntegerField(default=0, max_length=8, unique=True, verbose_name=' Nro. de Documento'),
        ),
    ]
