# Generated by Django 3.2.16 on 2023-02-02 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appRP', '0005_usuario_a_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario_a',
        ),
    ]
