# Generated by Django 3.2.16 on 2023-02-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRP', '0006_delete_usuario_a'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(max_length=250, upload_to='imagenes/'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='dni',
            field=models.PositiveIntegerField(default=0, unique=True, verbose_name=' Nro. de Documento'),
        ),
    ]
