# Generated by Django 3.2.16 on 2023-02-06 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRP', '0010_auto_20230206_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='altura',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='piso',
            field=models.IntegerField(default=0),
        ),
    ]
