# Generated by Django 3.2.16 on 2023-02-06 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRP', '0011_auto_20230206_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='altura',
            field=models.CharField(max_length=5),
        ),
    ]
