# Generated by Django 3.2.16 on 2023-02-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRP', '0012_alter_usuario_altura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='altura',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
    ]
