# Generated by Django 3.2.16 on 2023-02-06 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appRP', '0013_alter_usuario_altura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='altura',
        ),
    ]
