# Generated by Django 3.2.16 on 2023-02-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRP', '0002_alter_usuario_piso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='altura',
            field=models.IntegerField(blank=True),
        ),
    ]
