# Generated by Django 3.2.16 on 2023-02-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRP', '0003_alter_usuario_altura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='altura',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='piso',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
