# Generated by Django 3.2.16 on 2023-02-10 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRP', '0005_alter_usuario_piso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='piso',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
