# Generated by Django 3.2.16 on 2023-02-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRP', '0008_auto_20230220_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='slug',
            field=models.SlugField(default='', max_length=255),
        ),
    ]
