# Generated by Django 3.2.16 on 2023-02-23 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRP', '0010_auto_20230222_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='usuario',
        ),
        migrations.AddField(
            model_name='orden',
            name='altura',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='orden',
            name='calle',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='orden',
            name='cod_postal',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Codigo Postal'),
        ),
        migrations.AddField(
            model_name='orden',
            name='depto',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='orden',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='orden',
            name='first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='orden',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='orden',
            name='localidad',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='orden',
            name='piso',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
